// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcxktrhdbuorfgsdbeuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjeGt0cmhkYnVvcmZnc2RiZXVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MjU0MjUsImV4cCI6MjA2MDAwMTQyNX0.4gjVpeZGj-vve7VPJrvls0PU7HmqxCaMeVORnN9K1sQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);